// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApRHuttdYarMHnbNjSMnYDZ2xLWW_JMiA',
    appId: '1:915466423350:web:1a43859f9396c33162dc97',
    messagingSenderId: '915466423350',
    projectId: 'neuroconecta-app',
    authDomain: 'neuroconecta-app.firebaseapp.com',
    storageBucket: 'neuroconecta-app.firebasestorage.app',
    measurementId: 'G-HN9ENRDRNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOj7UuoY2SOafYY6AfubezKeJazXTVOsY',
    appId: '1:915466423350:android:ac713405515f360862dc97',
    messagingSenderId: '915466423350',
    projectId: 'neuroconecta-app',
    storageBucket: 'neuroconecta-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyIoO7rzHGKXJ2DKNIBjc1srTkJq2dOwo',
    appId: '1:915466423350:ios:8e2dd0796d355a3362dc97',
    messagingSenderId: '915466423350',
    projectId: 'neuroconecta-app',
    storageBucket: 'neuroconecta-app.firebasestorage.app',
    iosBundleId: 'com.example.neuroconecta2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyIoO7rzHGKXJ2DKNIBjc1srTkJq2dOwo',
    appId: '1:915466423350:ios:8e2dd0796d355a3362dc97',
    messagingSenderId: '915466423350',
    projectId: 'neuroconecta-app',
    storageBucket: 'neuroconecta-app.firebasestorage.app',
    iosBundleId: 'com.example.neuroconecta2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApRHuttdYarMHnbNjSMnYDZ2xLWW_JMiA',
    appId: '1:915466423350:web:0146743b6e78fab062dc97',
    messagingSenderId: '915466423350',
    projectId: 'neuroconecta-app',
    authDomain: 'neuroconecta-app.firebaseapp.com',
    storageBucket: 'neuroconecta-app.firebasestorage.app',
    measurementId: 'G-25LMH7GVCK',
  );
}
